# Generated by Django 2.2.6 on 2019-11-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('numero_viejo', models.CharField(max_length=30)),
                ('abrev_viejo', models.CharField(max_length=30)),
                ('numero_nuevo', models.CharField(max_length=30)),
                ('abrev_nuevo', models.CharField(max_length=30)),
                ('hora', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('num_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30)),
                ('abrev', models.CharField(max_length=30)),
            ],
        ),
    ]
