# Generated by Django 2.2.6 on 2019-10-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numero',
            old_name='abreviado',
            new_name='abrev',
        ),
    ]
