# Generated by Django 2.2.6 on 2019-10-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nums', '0003_auto_20191018_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numero',
            old_name='id',
            new_name='num_id',
        ),
    ]
